// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXa31oF2vt70hTyvDezQ-FSHVqF5MRtWI',
    appId: '1:187016761522:web:c4a731a1cbe9be0012f9ab',
    messagingSenderId: '187016761522',
    projectId: 'exam-final-c25f3',
    authDomain: 'exam-final-c25f3.firebaseapp.com',
    storageBucket: 'exam-final-c25f3.appspot.com',
    measurementId: 'G-HY2KRJ4Y4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6lsp0E7cwGiG16lbHHXguZyhg9KpVcVA',
    appId: '1:187016761522:android:ba72db2d99205d9012f9ab',
    messagingSenderId: '187016761522',
    projectId: 'exam-final-c25f3',
    storageBucket: 'exam-final-c25f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAYwYbhJ19QmE8QSAuUb9uoCdsrVnnmhc',
    appId: '1:187016761522:ios:80e156eb3f8e5fd612f9ab',
    messagingSenderId: '187016761522',
    projectId: 'exam-final-c25f3',
    storageBucket: 'exam-final-c25f3.appspot.com',
    iosBundleId: 'com.example.examFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAYwYbhJ19QmE8QSAuUb9uoCdsrVnnmhc',
    appId: '1:187016761522:ios:80e156eb3f8e5fd612f9ab',
    messagingSenderId: '187016761522',
    projectId: 'exam-final-c25f3',
    storageBucket: 'exam-final-c25f3.appspot.com',
    iosBundleId: 'com.example.examFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXa31oF2vt70hTyvDezQ-FSHVqF5MRtWI',
    appId: '1:187016761522:web:bafe8a393dcecf3d12f9ab',
    messagingSenderId: '187016761522',
    projectId: 'exam-final-c25f3',
    authDomain: 'exam-final-c25f3.firebaseapp.com',
    storageBucket: 'exam-final-c25f3.appspot.com',
    measurementId: 'G-VTCPCR8RL6',
  );
}
